codecov:
  ci:
    - !appveyor                # ignore CI builds by AppVeyor

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
